id: ''
dataname: MO
isTrain: true
snapshot: 50
data_dir: data
prepare_data: true
use_instance_seg: true
tb_dir: tensorboard
model:
  network: ResUNet34
  unet:
    add_coord: true
    filters:
    - 512
    - 256
    - 128
    - 64
    - 64
    - 64
    - 16
train:
  random_seed: 1
  n_epochs: 1000
  n_batches: 8
  select: aji
  label_type:
  - prob
  - voronoi
  label_type_channel:
  - 1
  - 3
  loss_type_weight:
  - 1.0
  - 1.0
  log_interval: 1
  optimizer: Adam
  momentum: 0.9
  lr: 0.001
  weight_decay: 0
  cutoff: 0.5
  start_epoch: 0
  checkpoint: ''
  check_start: 0
  add_bg: true
  bg_cutoff:
  - 0
  - 0.3
  bg_weight: 1
test:
  test_epoch: best
  save_flag: true
  patch_size: 224
  overlap: 80
  model_path: ''
  seg_model_path: checkpoints/MO/SPN/checkpoints/checkpoint_best.pth.tar
post:
  min_area: 20
  cluster_method: mean_shift
  cutoff: 0.3
  bandwidth: 1.5
  ins_post: true
transform_train:
  label_encoding: 1
